### ISSUE TITLE
Shifting menu

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#1453]
In the `dash` branch, I see a weird shifting of the leftnav when I click menu entries:

This reproes for me on MacOS using Chrome 73. I doesn't seem to repro when using Safari.

![glitch](https://user-images.githubusercontent.com/13644170/55951164-de6ae100-5c56-11e9-81af-df30598ca74c.gif)

**Comment by mit-mit** [comment]
cc @isoos @kwalrath I'm curious if you also see this?

**Comment by isoos** [comment]
I think in one frame the "Language" menu item is on the same level as the banner, and then it gets pushed below it. The repositioning happens in JavaScript, as we need to monitor the scrolling and may re-adjust the top position of the sidebar depending on how the banner is scrolling out of the view.

I don't know yet why the extra jump happens on page loads, but will investigate.

**Comment by kwalrath** [comment]
I see it, too, on Chrome 75. E.g. go to https://dartlang-org-staging-1.firebaseapp.com/guides/language/language-tour, then click different items in the left nav. Almost every time you go to a new page or reload, you'll see the shift. It takes longer to resolve on a long page like the language tour, but it's also visible on shorter pages.

In Safari 12.1, I see an initial positioning issue of the left & right columns wrt the banner on the language tour (our longest page), but not on other pages. Nothing untoward happens on reload, except when I'm viewing the language tour.

**Comment by isoos** [comment]
@kwalrath could you please build #1454 and share the link for it? I think we should see it fixed with that change.

**Comment by kwalrath** [comment]
Staged: https://kw-staging-dartlang-2.firebaseapp.com/guides/language/language-tour

It looks much better to me. Some of the other reload issues remain, but they're much smaller.

**Comment by kwalrath** [comment]
For the record, here are the other issues I see (much less of an issue than this one):

* In the left nav, the external window icon initially loads much larger than it ends up.
* In the banner, the text shifts position a bit.
* In the banner, the external window icon isn't initially visible. (I wouldn't say this is worth fixing, but I bet this is what causes the text shift. Workaround would be to use styles to eliminate the icon for this link.)

**Comment by isoos** [comment]
> - In the left nav, the external window icon initially loads much larger than it ends up.
> - In the banner, the text shifts position a bit.
> - In the banner, the external window icon isn't initially visible. (I wouldn't say this is worth fixing, but I bet this is what causes the text shift. Workaround would be to use styles to eliminate the icon for this link.)

I think these are all related to the way we add those icons: it is done via JavaScript, and of course after the page loads and displays, such changes do result in noticeable re-layout. The good solution would be to do that in the HTML output, I'll check what we can do about it...

**Comment by kwalrath** [comment]
The weird thing is: why are the large icons appearing in the sidenav? I'd expect them to be either not there, or in the same font the rest of the sidenav uses. I'm happy to work around the banner issue.

**Comment by kwalrath** [comment]
Mostly fixed by #1454. The issue still happens when you come into a page at an anchor, e.g. https://dartlang-org-staging-0.firebaseapp.com/guides/language/language-tour#keywords. I'm not sure how much we should worry about that, though.

**Comment by isoos** [comment]
> Although the main issue is mostly fixed by #1454, the problem still happens when you come into a page at an anchor

This repositioning is though. Btw. it is noticeable on [Flutter](https://flutter.dev/docs#new-to-flutter) too, e.g. by reloading the page while at an anchor. The jump happens because the banner is assumed to be visible on load, but as we are at an anchor, it is not, and the JS part updates the view. Couple of options and tradeoffs to consider:

1. Making the banner fixed (it won't scroll out of the view) - the top position would be fixed all the time, no sudden jumps on load.

2. Making the sidebar invisible at first, displaying it only after the JS updates it. It would still "flash", but it would be at its intended place. The bad part is that if the browser disables JS, it won't show at all.

3. Making the banner fit between the two sidebars. This would also allow us to use a fixed top position, and no jump on load happens.

**Comment by isoos** [comment]
> The weird thing is: why are the large icons appearing in the sidenav?

The template generates a markup `<i class="fas fa-external-link-alt"></i>`, which is later hidden, but only after a JS part triggers an update in their style. I can fix that.

However, the same JS adds the style to `<a>` elements to display the external link icon, which pushes the width of the text (e.g. in a banner), and that causes the weird jumps. I'm not yet sure how to fix that in jekyll.

**Comment by mit-mit** [comment]
@kwalrath in the current IA, aren't all the external links in the leftnav in that last 'Other sites' group? If so, I think we can simply remove the 'external link' decoration and now worry about all this complexity.

@isoos, with #1454 the jumping issue seems resolved, thanks much!

**Comment by kwalrath** [comment]
> @kwalrath in the current IA, aren't all the external links in the leftnav in that last 'Other sites' group? If so, I think we can simply remove the 'external link' decoration and now worry about all this complexity.

There are a couple of additional external links that aren't in the **Other sites** group, but I think we could [re]move them:

* **Packages > Package site**
   I think we can drop this, since it's a duplicate.
* **Development > Editors & debuggers > DartPad**
   We can/should move the DartPad link to **Other sites**, but we'd need to add an Overview page for Editors & debuggers — probably a good idea anyway.

**Comment by kwalrath** [comment]
The menu looks good with #1455, so I'm closing this. We can open issues later for further refinements.
